const tracks = [
    {
        id: 1,
        track: "Luigi Circuit",
        times: [
            {
                player: "Cole",
                time: "1:08:774",
                character: "Funky Kong",
                vehicle: "Spear",
            },
        ]
    },
    {
        id: 2,
        track: "Moo Moo Meadows",
        times: [
            {
                player: "Sosis",
                time: "1:15:483",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            },
        ]
    },
    {
        id: 3,
        track: "Mushroom Gorge",
        times: [
            {
                player: "Bryce",
                time: "0:20:320",
                character: "Baby Mario",
                vehicle: "Quacker",
            }
        ],
        nscTimes: [
            {
                player: "Connor",
                time: "1:40:741",
                character: "Funky Kong",
                vehicle: "Flame Runner"
            }
        ]
    },
    {
        id: 4,
        track: "Toad's Factory",
        times: [
            {
                player: "Logan",
                time: "1:44:406",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
        nscTimes: [
            {
                player: "Logan",
                time: "1:49:197",
                character: "Funky Kong",
                vehicle: "Flame Runner"
            }
        ]
    },
    {
        id: 5,
        track: "Mario Circuit",
        times: [
            {
                player: "Logan",
                time: "0:47:715",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
        nscTimes: [
            {
                player: "Guy",
                time: "1:20:357",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ]
    },
    {
        id: 6,
        track: "Coconut Mall",
        times: [
            {
                player: "Braixen",
                time: "0:31:481",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ],
        nscTimes: [
            {
                player: "Braixen",
                time: "1:55:573",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 7,
        track: "DK Summit",
        times: [
            {
                player: "Blake",
                time: "1:45:210",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
    },
    {
        id: 8,
        track: "Wario's Gold Mine",
        times: [
            {
                player: "Logan",
                time: "0:31:882",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
        nscTimes: [
            {
                player: "Vincent",
                time: "1:50:579",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 9,
        track: "Daisy Circuit",
        times: [
            {
                player: "Luke",
                time: "1:28:425",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ],
    },
    {
        id: 10,
        track: "Koopa Cape",
        times: [
            {
                player: "Justin",
                time: "2:14:552",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
        nscTimes: [
            {
                player: "Jongwoo",
                time: "2:17:951",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 11,
        track: "Maple Treeway",
        times: [
            {
                player: "Des",
                time: "1:34:999",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
        nscTimes: [
            {
                player: "Demon",
                time: "2:14:507",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 12,
        track: "Grumble Volcano",
        times: [
            {
                player: "Niyake",
                time: "0:15:962",
                character: "Baby Mario",
                vehicle: "Quacker",
            }
        ],
        nscTimes: [
            {
                player: "Barney",
                time: "1:51:542",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 13,
        track: "Dry Dry Ruins",
        times: [
            {
                player: "Justin",
                time: "1:46:972",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
    },
    {
        id: 14,
        track: "Moonview Highway",
        times: [
            {
                player: "Luke",
                time: "1:43:035",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
    },
    {
        id: 15,
        track: "Bowser's Castle",
        times: [
            {
                player: "Jared2K",
                time: "2:09:074",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ],
        nscTimes: [
            {
                player: "Zeke",
                time: "2:20:524",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 16,
        track: "Rainbow Road",
        times: [
            {
                player: "Logan",
                time: "2:10:051",
                character: "Baby Daisy",
                vehicle: "Quacker",
            }
        ],
        nscTimes: [
            {
                player: "Kaede",
                time: "2:24:650",
                character: "Funky Kong",
                vehicle: "Flame Flyer",
            }
        ]
    },
    {
        id: 17,
        track: "GCN Peach Beach",
        times: [
            {
                player: "Arrow",
                time: "1:00:049",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
        nscTimes: [
            {
                player: "Kasey",
                time: "1:12:686",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ]
    },
    {
        id: 18,
        track: "DS Yoshi Falls",
        times: [
            {
                player: "David",
                time: "0:58:648",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
    },
    {
        id: 19,
        track: "SNES Ghost Valley 2",
        times: [
            {
                player: "Logan",
                time: "0:49:992",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
        nscTimes: [
            {
                player: "Sosis",
                time: "0:52:775",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 20,
        track: "N64 Mario Raceway",
        times: [
            {
                player: "Sosis",
                time: "1:41:198",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
    },
    {
        id: 21,
        track: "N64 Sherbet Land",
        times: [
            {
                player: "Arthur",
                time: "1:16:907",
                character: "Toadette",
                vehicle: "Magikruiser",
            }
        ],
        nscTimes: [
            {
                player: "Sosis",
                time: "2:03:750",
                character: "Toadette",
                vehicle: "Magikruiser",
            }
        ]
    },
    {
        id: 22,
        track: "GBA Shy Guy Beach",
        times: [
            {
                player: "Sosis",
                time: "1:21:496",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
    },
    {
        id: 23,
        track: "DS Delfino Square",
        times: [
            {
                player: "Luke",
                time: "2:03:799",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
    },
    {
        id: 24,
        track: "GCN Waluigi Stadium",
        times: [
            {
                player: "Hunter",
                time: "1:39:438",
                character: "Baby Daisy",
                vehicle: "Bullet Bike",
            }
        ],
        nscTimes: [
            {
                player: "Connor",
                time: "1:48:433",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 25,
        track: "DS Desert Hills",
        times: [
            {
                player: "Justin",
                time: "1:30:990",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
        nscTimes: [
            {
                player: "Sosis",
                time: "1:34:397",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 26,
        track: "GBA Bowser Castle 3",
        times: [
            {
                player: "Luke",
                time: "1:57:335",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
        nscTimes: [
            {
                player: "Luke",
                time: "2:16:366",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
    {
        id: 27,
        track: "N64 DK's Jungle Parkway",
        times: [
            {
                player: "Invincible",
                time: "0:41:072",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ],
        nscTimes: [
            {
                player: "Luke",
                time: "2:11:117",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ]
    },
    {
        id: 28,
        track: "GCN Mario Circuit",
        times: [
            {
                player: "Luke",
                time: "1:30:513",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ],
    },
    {
        id: 29,
        track: "SNES Mario Circuit 3",
        times: [
            {
                player: "Luke",
                time: "1:17:889",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ],
    },
    {
        id: 30,
        track: "DS Peach Gardens",
        times: [
            {
                player: "King Alex",
                time: "1:58:986",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
    },
    {
        id: 31,
        track: "GCN DK Mountain",
        times: [
            {
                player: "Logan",
                time: "1:58:335",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ],
        nscTimes: [
            {
                player: "Logan",
                time: "2:05:194",
                character: "Daisy",
                vehicle: "Mach Bike",
            }
        ]
    },
    {
        id: 32,
        track: "N64 Bowser's Castle",
        times: [
            {
                player: "Logan",
                time: "2:20:584",
                character: "Funky Kong",
                vehicle: "Spear",
            }
        ],
        nscTimes: [
            {
                player: "Luke",
                time: "2:30:637",
                character: "Funky Kong",
                vehicle: "Flame Runner",
            }
        ]
    },
];

const vehicles = [
    {
        id: 1,
        name: 'Blue Falcon',
        type: 'cart',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 60,
        weight: 29,
        acceleration: 35,
        handling: 29,
        drift: 43,
        offRoad: 24,
        miniTurbo: 29,
        total: 249,
    },
    {
        id: 2,
        name: 'Booster Seat',
        type: 'cart',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 27,
        weight: 27,
        acceleration: 56,
        handling: 64,
        drift: 37,
        offRoad: 54,
        miniTurbo: 59,
        total: 324,
    },
    {
        id: 3,
        name: 'Cheep Charger',
        type: 'cart',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 34,
        weight: 24,
        acceleration: 64,
        handling: 56,
        drift: 59,
        offRoad: 45,
        miniTurbo: 54,
        total: 336,
    },
    {
        id: 4,
        name: 'Mini Beast',
        type: 'cart',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 55,
        weight: 32,
        acceleration: 29,
        handling: 32,
        drift: 64,
        offRoad: 27,
        miniTurbo: 64,
        total: 303,
    },
    {
        id: 5,
        name: 'Standard Kart S',
        type: 'cart',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 41,
        weight: 29,
        acceleration: 48,
        handling: 48,
        drift: 51,
        offRoad: 40,
        miniTurbo: 45,
        total: 302,
    },
    {
        id: 6,
        name: 'Tiny Titan',
        type: 'cart',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 46,
        weight: 35,
        acceleration: 43,
        handling: 43,
        drift: 29,
        offRoad: 64,
        miniTurbo: 40,
        total: 300,
    },
    {
        id: 7,
        name: 'Bit Bike',
        type: 'Bike',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 25,
        weight: 18,
        acceleration: 59,
        handling: 67,
        drift: 40,
        offRoad: 56,
        miniTurbo: 62,
        total: 327,
    },
    {
        id: 8,
        name: 'Bullet Bike',
        type: 'Bike',
        weightClass: 'light',
        driftStyle: 'inside',
        speed: 53,
        weight: 24,
        acceleration: 32,
        handling: 35,
        drift: 67,
        offRoad: 29,
        miniTurbo: 67,
        total: 307,
    },
    {
        id: 9,
        name: 'Jet Bubble',
        type: 'Bike',
        weightClass: 'light',
        driftStyle: 'inside',
        speed: 48,
        weight: 27,
        acceleration: 40,
        handling: 40,
        drift: 45,
        offRoad: 35,
        miniTurbo: 37,
        total: 272,
    },
    {
        id: 10,
        name: 'Magikruiser',
        type: 'Bike',
        weightClass: 'light',
        driftStyle: 'inside',
        speed: 43,
        weight: 24,
        acceleration: 45,
        handling: 45,
        drift: 32,
        offRoad: 67,
        miniTurbo: 43,
        total: 299,
    },
    {
        id: 11,
        name: 'Quacker',
        type: 'Bike',
        weightClass: 'light',
        driftStyle: 'inside',
        speed: 32,
        weight: 17,
        acceleration: 67,
        handling: 60,
        drift: 62,
        offRoad: 48,
        miniTurbo: 57,
        total: 343,
    },
    {
        id: 12,
        name: 'Standard Bike S',
        type: 'Bike',
        weightClass: 'light',
        driftStyle: 'outside',
        speed: 39,
        weight: 21,
        acceleration: 51,
        handling: 51,
        drift: 54,
        offRoad: 43,
        miniTurbo: 48,
        total: 307,
    },
    {
        id: 13,
        name: 'Classic Dragster',
        type: 'cart',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 37,
        weight: 43,
        acceleration: 59,
        handling: 54,
        drift: 54,
        offRoad: 40,
        miniTurbo: 51,
        total: 338,
    },
    {
        id: 14,
        name: 'Daytripper',
        type: 'cart',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 34,
        weight: 45,
        acceleration: 51,
        handling: 59,
        drift: 32,
        offRoad: 48,
        miniTurbo: 54,
        total: 323,
    },
    {
        id: 15,
        name: 'Sprinter',
        type: 'cart',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 64,
        weight: 48,
        acceleration: 27,
        handling: 24,
        drift: 37,
        offRoad: 21,
        miniTurbo: 24,
        total: 245,
    },
    {
        id: 16,
        name: 'Standard Kart M',
        type: 'cart',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 46,
        weight: 45,
        acceleration: 40,
        handling: 43,
        drift: 45,
        offRoad: 35,
        miniTurbo: 40,
        total: 294,
    },
    {
        id: 17,
        name: 'Super Blooper',
        type: 'cart',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 50,
        weight: 40,
        acceleration: 35,
        handling: 37,
        drift: 21,
        offRoad: 54,
        miniTurbo: 35,
        total: 272,
    },
    {
        id: 18,
        name: 'Wild Wing',
        type: 'cart',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 57,
        weight: 51,
        acceleration: 21,
        handling: 29,
        drift: 59,
        offRoad: 24,
        miniTurbo: 59,
        total: 300,
    },
    {
        id: 19,
        name: 'Dolphin Dasher',
        type: 'bike',
        weightClass: 'medium',
        driftStyle: 'inside',
        speed: 48,
        weight: 43,
        acceleration: 37,
        handling: 40,
        drift: 24,
        offRoad: 56,
        miniTurbo: 37,
        total: 285,
    },
    {
        id: 20,
        name: 'Mach Bike',
        type: 'bike',
        weightClass: 'medium',
        driftStyle: 'inside',
        speed: 55,
        weight: 37,
        acceleration: 24,
        handling: 32,
        drift: 62,
        offRoad: 27,
        miniTurbo: 62,
        total: 299,
    },
    {
        id: 21,
        name: 'Sneakster',
        type: 'bike',
        weightClass: 'medium',
        driftStyle: 'inside',
        speed: 62,
        weight: 40,
        acceleration: 29,
        handling: 27,
        drift: 40,
        offRoad: 24,
        miniTurbo: 27,
        total: 249,
    },
    {
        id: 22,
        name: 'Standard Bike M',
        type: 'bike',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 43,
        weight: 37,
        acceleration: 43,
        handling: 45,
        drift: 48,
        offRoad: 37,
        miniTurbo: 43,
        total: 296,
    },
    {
        id: 23,
        name: 'Sugarscoot',
        type: 'bike',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 32,
        weight: 32,
        acceleration: 54,
        handling: 62,
        drift: 35,
        offRoad: 51,
        miniTurbo: 56,
        total: 322,
    },
    {
        id: 24,
        name: 'Zip Zip',
        type: 'bike',
        weightClass: 'medium',
        driftStyle: 'outside',
        speed: 41,
        weight: 35,
        acceleration: 45,
        handling: 51,
        drift: 29,
        offRoad: 62,
        miniTurbo: 45,
        total: 308,
    },
    {
        id: 25,
        name: 'Flame Flyer',
        type: 'cart',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 62,
        weight: 59,
        acceleration: 16,
        handling: 21,
        drift: 48,
        offRoad: 18,
        miniTurbo: 48,
        total: 272,
    },
    {
        id: 26,
        name: 'Honey Coupe',
        type: 'cart',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 53,
        weight: 62,
        acceleration: 27,
        handling: 29,
        drift: 56,
        offRoad: 24,
        miniTurbo: 56,
        total: 307,
    },
    {
        id: 27,
        name: 'Jetsetter',
        type: 'cart',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 69,
        weight: 56,
        acceleration: 21,
        handling: 17,
        drift: 27,
        offRoad: 16,
        miniTurbo: 16,
        total: 222,
    },
    {
        id: 28,
        name: 'Offroader',
        type: 'cart',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 39,
        weight: 64,
        acceleration: 48,
        handling: 54,
        drift: 18,
        offRoad: 43,
        miniTurbo: 45,
        total: 311,
    },
    {
        id: 29,
        name: 'Piranha Prowler',
        type: 'cart',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 55,
        weight: 67,
        acceleration: 29,
        handling: 35,
        drift: 35,
        offRoad: 29,
        miniTurbo: 27,
        total: 277,
    },
    {
        id: 30,
        name: 'Standard Kart L',
        type: 'cart',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 48,
        weight: 59,
        acceleration: 37,
        handling: 40,
        drift: 40,
        offRoad: 35,
        miniTurbo: 35,
        total: 294,
    },
    {
        id: 31,
        name: 'Flame Runner',
        type: 'bike',
        weightClass: 'heavy',
        driftStyle: 'inside',
        speed: 60,
        weight: 54,
        acceleration: 18,
        handling: 24,
        drift: 51,
        offRoad: 21,
        miniTurbo: 51,
        total: 279,
    },
    {
        id: 32,
        name: 'Phantom',
        type: 'bike',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 43,
        weight: 51,
        acceleration: 43,
        handling: 48,
        drift: 17,
        offRoad: 56,
        miniTurbo: 40,
        total: 298,
    },
    {
        id: 33,
        name: 'Shooting Star',
        type: 'bike',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 50,
        weight: 48,
        acceleration: 29,
        handling: 32,
        drift: 59,
        offRoad: 27,
        miniTurbo: 59,
        total: 304,
    },
    {
        id: 34,
        name: 'Spear',
        type: 'bike',
        weightClass: 'heavy',
        driftStyle: 'inside',
        speed: 67,
        weight: 56,
        acceleration: 24,
        handling: 18,
        drift: 29,
        offRoad: 18,
        miniTurbo: 18,
        total: 230,
    },
    {
        id: 35,
        name: 'Standard Bike L',
        type: 'bike',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 46,
        weight: 54,
        acceleration: 40,
        handling: 43,
        drift: 43,
        offRoad: 37,
        miniTurbo: 37,
        total: 300,
    },
    {
        id: 36,
        name: 'Wario Bike',
        type: 'bike',
        weightClass: 'heavy',
        driftStyle: 'outside',
        speed: 37,
        weight: 59,
        acceleration: 51,
        handling: 56,
        drift: 21,
        offRoad: 45,
        miniTurbo: 48,
        total: 317,
    },
];

const characters = [
    {
        id: 1,
        name: 'Baby Daisy',
        weightClass: 'light',
        speed: 5,
        weight: 6,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 0,
        miniTurbo: 3,
        total: 14,
    },
    {
        id: 2,
        name: 'Baby Luigi',
        weightClass: 'light',
        speed: 5,
        weight: 8,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 0,
        miniTurbo: 0,
        total: 13,
    },
    {
        id: 3,
        name: 'Baby Mario',
        weightClass: 'light',
        speed: 0,
        weight: 8,
        acceleration: 0,
        handling: 6,
        drift: 0,
        offRoad: 0,
        miniTurbo: 0,
        total: 14,
    },
    {
        id: 4,
        name: 'Baby Peach',
        weightClass: 'light',
        speed: 3,
        weight: 6,
        acceleration: 3,
        handling: 3,
        drift: 0,
        offRoad: 0,
        miniTurbo: 0,
        total: 15,
    },
    {
        id: 5,
        name: 'Dry Bones',
        weightClass: 'light',
        speed: 0,
        weight: 0,
        acceleration: 3,
        handling: 0,
        drift: 3,
        offRoad: 0,
        miniTurbo: 6,
        total: 12,
    },
    {
        id: 6,
        name: 'Koopa Troopa',
        weightClass: 'light',
        speed: 0,
        weight: 0,
        acceleration: 0,
        handling: 3,
        drift: 0,
        offRoad: 0,
        miniTurbo: 6,
        total: 9,
    },
    {
        id: 7,
        name: 'Mii (Light)',
        weightClass: 'light',
        speed: 3,
        weight: 3,
        acceleration: 0,
        handling: 0,
        drift: 3,
        offRoad: 0,
        miniTurbo: 3,
        total: 12,
    },
    {
        id: 8,
        name: 'Toad',
        weightClass: 'light',
        speed: 0,
        weight: 0,
        acceleration: 6,
        handling: 0,
        drift: 6,
        offRoad: 0,
        miniTurbo: 0,
        total: 12,
    },
    {
        id: 9,
        name: 'Toadette',
        weightClass: 'light',
        speed: 3,
        weight: 0,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 6,
        miniTurbo: 0,
        total: 9,
    },
    {
        id: 10,
        name: 'Birdo',
        weightClass: 'medium',
        speed: 0,
        weight: 3,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 3,
        miniTurbo: 5,
        total: 11,
    },
    {
        id: 11,
        name: 'Bowser Jr.',
        weightClass: 'medium',
        speed: 0,
        weight: 0,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 3,
        miniTurbo: 3,
        total: 6,
    },
    {
        id: 12,
        name: 'Daisy',
        weightClass: 'medium',
        speed: 4,
        weight: 0,
        acceleration: 0,
        handling: 2,
        drift: 0,
        offRoad: 0,
        miniTurbo: 3,
        total: 9,
    },
    {
        id: 13,
        name: 'Diddy Kong',
        weightClass: 'medium',
        speed: 0,
        weight: 0,
        acceleration: 3,
        handling: 0,
        drift: 3,
        offRoad: 0,
        miniTurbo: 5,
        total: 11,
    },
    {
        id: 14,
        name: 'Luigi',
        weightClass: 'medium',
        speed: 2,
        weight: 6,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 0,
        miniTurbo: 0,
        total: 8,
    },
    {
        id: 15,
        name: 'Mario',
        weightClass: 'medium',
        speed: 0,
        weight: 6,
        acceleration: 2,
        handling: 2,
        drift: 3,
        offRoad: 0,
        miniTurbo: 0,
        total: 13,
    },
    {
        id: 16,
        name: 'Mii (Medium)',
        weightClass: 'medium',
        speed: 3,
        weight: 3,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 3,
        miniTurbo: 3,
        total: 12,
    },
    {
        id: 17,
        name: 'Peach',
        weightClass: 'medium',
        speed: 2,
        weight: 0,
        acceleration: 5,
        handling: 0,
        drift: 6,
        offRoad: 0,
        miniTurbo: 0,
        total: 13,
    },
    {
        id: 18,
        name: 'Yoshi',
        weightClass: 'medium',
        speed: 0,
        weight: 3,
        acceleration: 0,
        handling: 0,
        drift: 3,
        offRoad: 5,
        miniTurbo: 0,
        total: 11,
    },
    {
        id: 19,
        name: 'Bowser',
        weightClass: 'heavy',
        speed: 2,
        weight: 5,
        acceleration: 0,
        handling: 0,
        drift: 3,
        offRoad: 0,
        miniTurbo: 0,
        total: 10,
    },
    {
        id: 20,
        name: 'Donkey Kong',
        weightClass: 'heavy',
        speed: 0,
        weight: 3,
        acceleration: 2,
        handling: 2,
        drift: 0,
        offRoad: 0,
        miniTurbo: 3,
        total: 10,
    },
    {
        id: 21,
        name: 'Dry Bowser',
        weightClass: 'heavy',
        speed: 0,
        weight: 0,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 6,
        miniTurbo: 6,
        total: 12,
    },
    {
        id: 22,
        name: 'Funky Kong',
        weightClass: 'heavy',
        speed: 4,
        weight: 0,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 3,
        miniTurbo: 0,
        total: 7,
    },
    {
        id: 23,
        name: 'King Boo',
        weightClass: 'heavy',
        speed: 0,
        weight: 0,
        acceleration: 0,
        handling: 5,
        drift: 0,
        offRoad: 3,
        miniTurbo: 0,
        total: 8,
    },
    {
        id: 24,
        name: 'Mii (Heavy)',
        weightClass: 'heavy',
        speed: 3,
        weight: 0,
        acceleration: 3,
        handling: 3,
        drift: 3,
        offRoad: 0,
        miniTurbo: 0,
        total: 12,
    },
    {
        id: 25,
        name: 'Rosalina',
        weightClass: 'heavy',
        speed: 3,
        weight: 0,
        acceleration: 0,
        handling: 3,
        drift: 0,
        offRoad: 0,
        miniTurbo: 3,
        total: 9,
    },
    {
        id: 26,
        name: 'Waluigi',
        weightClass: 'heavy',
        speed: 0,
        weight: 0,
        acceleration: 6,
        handling: 0,
        drift: 5,
        offRoad: 3,
        miniTurbo: 0,
        total: 14,
    },
    {
        id: 27,
        name: 'Wario',
        weightClass: 'heavy',
        speed: 0,
        weight: 3,
        acceleration: 0,
        handling: 0,
        drift: 0,
        offRoad: 3,
        miniTurbo: 6,
        total: 12,
    },
];

module.exports = { tracks, vehicles, characters };